blank_issues_enabled: true
contact_links:
  - name: SC-DEX Discussions
    url: https://github.com/opensupplyhub/supplychaindata.exchange/discussions
    about: Please ask and answer questions about extensions here.
